CREATE TABLE IF NOT EXISTS portefolio (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    gurl TEXT NOT NULL,
    yurl TEXT NOT NULL,
    file TEXT NOT NULL,
    subcategory TEXT NOT NULL,
    dato TEXT NOT NULL DEFAULT CURRENT_DATE);

CREATE TABLE IF NOT EXISTS webdevelopment(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    gurl TEXT NOT NULL,
    yurl TEXT NOT NULL DEFAULT false,
    dato TEXT NOT NULL DEFAULT CURRENT_DATE);

CREATE TABLE cookies IF NOT EXISTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    txtfile BLOB NOT NULL,
    dd TIMESTAMP NOT NULL,
    dato TEXT NOT NULL DEFAULT CURRENT_DATE);
    
)