# Generated by Django 4.0.4 on 2022-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0002_rename_category_blogcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordbots',
            name='link',
            field=models.TextField(default='/img/logo/python.svg'),
        ),
    ]
