# Generated by Django 4.0.4 on 2022-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0003_alter_discordbots_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordbots',
            name='link',
            field=models.TextField(),
        ),
    ]
