# Generated by Django 4.0.4 on 2022-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0004_alter_discordbots_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='img',
            field=models.FilePathField(default='/static/svg/icons/', path='/svg'),
        ),
    ]
