# Generated by Django 4.0.4 on 2022-05-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0005_blogcategory_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='img',
        ),
    ]
