# Generated by Django 4.0.4 on 2022-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0006_remove_blogcategory_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordbots',
            name='link',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.TextField(default='https://discord.com/api/oauth2/authorize?client_id=903619759587852338&permissions=8&scope=bot'),
        ),
    ]
