# Generated by Django 4.0.4 on 2022-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0007_remove_discordbots_link_blogpost_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.TextField(default='krigjo25'),
        ),
    ]
