# Generated by Django 4.0.4 on 2022-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0008_blogpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='link',
            new_name='bot',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='readme',
            field=models.TextField(default='https://github.com/krigjo25/Discord'),
        ),
    ]
