# Generated by Django 4.0.4 on 2022-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0011_blogpost_imglink_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imglink',
            field=models.FilePathField(default='img/svg/', path='/static'),
        ),
    ]
