# Generated by Django 4.0.4 on 2022-05-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0012_alter_blogpost_imglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='imglink',
        ),
    ]
